###
POST http://localhost:3000/personel
Content-Type: application/json

{
    "firstName": "Margarette",
    "lastName": "Xion"
}

###
GET http://localhost:3000/personel


###
GET http://localhost:3000/personel/6408da5aa841eb69e973a048